on: workflow_dispatch
jobs:
  export:
    runs-on: macos-26
    steps:
      - run: |
          mkdir -p ~/runtime
          cp "/System/Library/AssetsV2/com_apple_MobileAsset_iOSSimulatorRuntime/af14d04fa4f5b29c2471951b01491c6403eab68f.asset/AssetData/Restore/iOSSimulatorRuntime_Cryptex.dmg" ~/runtime/iOS_26.5_Simulator_Runtime.dmg
      - uses: actions/upload-artifact@v4
        with:
          name: ios-26.5-runtime
          path: ~/runtime
          retention-days: 1
