on: workflow_dispatch
jobs:
  export:
    runs-on: macos-26
    steps:
      - run: |
          cp -R "/Library/Developer/CoreSimulator/Volumes/iOS_23F77/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 26.5.simruntime" ~/runtime
      - uses: actions/upload-artifact@v4
        with:
          name: ios-26.5-runtime
          path: ~/runtime
          retention-days: 1
